# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: freehand-os
description: Freehand 1.0 - Built on Open BL Architecture
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  # This copies everything from your repo's files/system/ folder into the OS
  - type: files
    files:
      - source: system
        destination: /

  # This installs the handheld daemons and your C++ Qt dependencies
  - type: dnf
    install:
      packages:
        - hhd
        - gamescope
        - qt6-qtbase
        - qt6-qtdeclarative
        - qt6-qtwayland
